# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ msodbcsql_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  environment: "{{ msodbcsql_apt_environment }}"
  tags:
    - msodbcsql-install-dependencies

- name: install | additional
  ansible.builtin.apt:
    name: "{{ msodbcsql_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  environment: "{{ msodbcsql_apt_environment }}"
  tags:
    - msodbcsql-install-additional
