# tasks file
---
- name: include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - msodbcsql

- name: version support
  ansible.builtin.import_tasks: version-support.yml
  tags:
    - configuration
    - msodbcsql
    - msodbcsql-version-support

- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - msodbcsql
    - msodbcsql-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - msodbcsql
    - msodbcsql-install
