# tasks file
---
- name: version support
  ansible.builtin.import_tasks: version-support.yml
  tags:
    - configuration
    - msodbcsql
    - msodbcsql-version-support

- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - msodbcsql
    - msodbcsql-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - msodbcsql
    - msodbcsql-install
